# Generated by Django 4.0.6 on 2024-12-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='created',
        ),
        migrations.AddField(
            model_name='notes',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
